use SALON;

SELECT * FROM dbo.EMPLOYEES;
SELECT * FROM dbo.CLIENTS;
SELECT * FROM dbo.SERVICS;
SELECT * FROM dbo.REGISTRATION;
SELECT * FROM dbo.REVIEWS;

CREATE TABLE CLIENTS (
    clientID INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(50) NOT NULL,
    surname NVARCHAR(50) NOT NULL,
    phone NVARCHAR(20) NOT NULL,
    email NVARCHAR(100) UNIQUE NOT NULL,
    password NVARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE EMPLOYEES (
    employeeID INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(50) NOT NULL,
    surname NVARCHAR(50) NOT NULL,
    positions NVARCHAR(50) NOT NULL,
    serviceID INT NOT NULL,
    phone NVARCHAR(20) NOT NULL,
    email NVARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE SERVICS (
    serviceID INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(100) UNIQUE NOT NULL,
    description NVARCHAR(255),    
    price DECIMAL(10,2) NOT NULL CHECK (price >= 0)
);

CREATE TABLE REVIEWS (
    reviewID INT IDENTITY(1,1) PRIMARY KEY,    
    employeeID INT NOT NULL,    
    rating INT CHECK (rating >= 1 AND rating <= 5),    
    comm NVARCHAR(255)
);

CREATE TABLE REGISTRATION (    
    registrationID INT IDENTITY(1,1) PRIMARY KEY,    
    clientID INT NOT NULL,    
    employeeID INT NOT NULL,
    dateTime DATETIME2 NOT NULL,    
    notes NVARCHAR(255)
);

-- ƒобавление внешних ключей 
ALTER TABLE REVIEWS 
ADD CONSTRAINT FK_Reviews_Employee 
FOREIGN KEY (employeeID) 
REFERENCES EMPLOYEES(employeeID) 
ON DELETE CASCADE;

ALTER TABLE REGISTRATION 
ADD CONSTRAINT FK_Registration_Client 
FOREIGN KEY (clientID) 
REFERENCES CLIENTS(clientID) 
ON DELETE CASCADE;

ALTER TABLE REGISTRATION 
ADD CONSTRAINT FK_Registration_Employee 
FOREIGN KEY (employeeID) 
REFERENCES EMPLOYEES(employeeID) 
ON DELETE CASCADE;

ALTER TABLE EMPLOYEES 
ADD CONSTRAINT FK_Employee_Service 
FOREIGN KEY (serviceID) 
REFERENCES SERVICS(serviceID) 
ON DELETE CASCADE;

--удаление ограничени€ внешних ключей
ALTER TABLE REGISTRATION 
DROP CONSTRAINT FK_Registration_Client;

ALTER TABLE REGISTRATION 
DROP CONSTRAINT FK_Registration_Employee;

ALTER TABLE REVIEWS 
DROP CONSTRAINT FK_Reviews_Employee;

ALTER TABLE EMPLOYEES 
DROP CONSTRAINT FK_Employee_Service;

--удаление содержимого таблиц
TRUNCATE TABLE REGISTRATION;
TRUNCATE TABLE SERVICS;
TRUNCATE TABLE EMPLOYEES;
TRUNCATE TABLE CLIENTS;
TRUNCATE TABLE REVIEWS;

--удаление таблиц
drop table CLIENTS;
drop table EMPLOYEES;
drop table SERVICS;
drop table REVIEWS;
drop table REGISTRATION;